### ISSUE TITLE
Corpus not accessible (403)

### ISSUE THREAD

**Issue by andreasvc** [evanmiltenburg/Dutch-corpora#1]
This link in the README: http://kyoto.let.vu.nl/~miltenburg/public_data/overheid/

... gives an error. Is there an alternative location?

**Comment by evanmiltenburg** [comment]
Hi Andreas!

Long time no see! (COLING 2018?) 

I am not aware of any alternative location. This was a corpus that I created as a hobby, so it's not something that we published somewhere like Zenodo, Figshare, or the TST-Centrale. You can recreate the corpus by following the [README](https://github.com/evanmiltenburg/Dutch-corpora/blob/master/overheid/README.md).

There are a couple of things I would do differently nowadays. For example: 
* Speakers aren't recorded, even though this is useful information.
* Sentences are selected based on their length, during the creation of the corpus rather than afterwards.
* Tokenisation is done using the NLTK.

I hope that helps!

**Comment by evanmiltenburg** [comment]
Maybe someone at the VU might be able to find the corpus, e.g. Marten Postma. (Just search the server for the filename in the URL.) But I'd recommend creating an up-to-date version, since there are 5 more years of data that aren't in the corpus yet.

**Comment by andreasvc** [comment]
Thanks for the response. I tried running the scripts, but I get an error message related to an SSH key. Don't know if I have time to debug this script, this is for an assignment for my students for tomorrow. Cheers!

**Comment by evanmiltenburg** [comment]
Hmm.. Het lijkt erop dat de ftp-server niet bereikbaar is. Dat zou betekenen dat ze ergens tussen 2015 en nu opgehouden zijn met de bulk uitleverservice (BUS). Heel jammer, want dit werkte erg fijn.
